### ISSUE TITLE
Before public release checklist

### ISSUE THREAD

**Issue by graysonwhite** [USDAForestService/FIESTA#9]
This is a checklist for tasks that must be completed before public release of `FIESTA` on GitHub.

- [x] Fix all examples: both make sense and run fast (<5s)
- [ ] Get `pkgdown` site ready to go with vignettes working and other tutorials included
    - vignettes other tutorials could include: (1) going through the flow of custom boundary to a post-strat, and (2) comparison to EVALIDATOR
- [ ] Extensive code checking
